# Key in order to upload dataset
key: MoQx74NBnJlkP0Av3R

# Dataverse API configuration
dataverse:
  url: https://datasets.socialhistory.org
  connectTimeoutMs: 5000
  readTimeoutMs: 10000

# Cache configuration
cache:
  maximumSize: 100
  maxHoursAccessTime: 12

# Configuration specific to rendering labour relation treemaps
labour:
  # Configuration reading labour relation XLSX files
  xlsx:
    empty: NA
    columns:
      year: year
      total: total
      country: country
      labourRelationLevel1: labour_rel_01
      labourRelationLevel2: labour_rel_02
      labourRelationLevel3: labour_rel_03
    virtualColumns:
      labRel11: txt1.1
      labRel12: txt1.2
      labRel13: txt1.3.ext
      labRel21: txt2.1
      labRel22: txt2.2
      labRel23: txt2.3.ext
      labRel31: txt3.1
      labRel32: txt3.2
      labRel33: txt3.3.ext
      code: code
      labRelMultiple11: txt1.1.mul
      labRelMultiple12: txt1.2.mul
      labRelMultiple13: txt1.3.ext.mul
      labRelMultiple21: txt2.1.mul
      labRelMultiple22: txt2.2.mul
      labRelMultiple23: txt2.3.ext.mul
      labRelMultiple31: txt3.1.mul
      labRelMultiple32: txt3.2.mul
      labRelMultiple33: txt3.3.ext.mul
      codeMultiple: code.mul
      color: color
      bmyear: bmyear
      continent: continent
  # Configuration creating treemaps for labour relation datasets
  treemap:
    rootLabel: Total population
    labels:
      year: Year
      bmyear: Cross section years
      continent: Continents
      country: Countries
    empty:
      txt2.1: No secondary labour relation available
      txt3.1: No third labour relation available
    suffix:
      txt2.1: (2nd)
      txt3.1: (3rd)
    multiples:
      txt1.1: txt1.1.mul
      txt1.2: txt1.2.mul
      txt1.3.ext: txt1.3.ext.mul
      txt2.1: txt2.1.mul
      txt2.2: txt2.2.mul
      txt2.3.ext: txt2.3.ext.mul
      txt3.1: txt3.1.mul
      txt3.2: txt3.2.mul
      txt3.3.ext: txt3.3.ext.mul
      code: code.mul

# Labour relations code translation
labourRelations:
  # Labour relation codes
  codes:
    1: Cannot work or cannot be expected to work (1)
    2: Affluent (2)
    3: Unemployed (3)
    4a: Leading producers (4a)
    4b: Kin producers (4b)
    5: Kin non-producers (5)
    6: Servants (6)
    7: Redistributive labourers (7)
    8: Obligatory labourers (8)
    9: Indentured tributary labourers (9)
    10: Tributary serfs (10)
    11: Tributary slaves (11)
    12a: Self-employed leading producers (12a)
    12b: Self-employed kin producers (12b)
    13: Employers (13)
    131: Employers (13)
    132: Employers (13)
    133: Employers (13)
    134: Employers (13)
    14: Wage earners for the market (14)
    141: Wage earners for the market (14)
    142: Wage earners for the market (14)
    143: Wage earners for the market (14)
    144: Wage earners for the market (14)
    15: Indentured labour (15)
    16: Serfs (16)
    17: Slaves (17)
    171: Slaves (17)
    172: Slaves (17)
    18: Wage earners for non-market institutions (18)
    181: Wage earners for non-market institutions (18)
    182: Wage earners for non-market institutions (18)
    183: Wage earners for non-market institutions (18)

  # First level (Type of exchange)
  level1:
    - label: Non-working
      color: "#9BCB41"
      code: N
      range:
        - 1
        - 3
    - label: Reciprocal labour
      color: "#E77347"
      code: R
      range:
        - 4
        - 7
    - label: Tributary labour
      color: "#F389AB"
      code: T
      range:
        - 8
        - 11
    - label: Commodified labour
      color: "#24B186"
      code: C
      range:
        - 12
        - 18

  # Second level (Goal of production)
  level2:
    - label: Non-working
      range:
        - 1
        - 3
    - label: Reciprocal labour
      range:
        - 4
        - 7
    - label: Tributary labour
      range:
        - 8
        - 11
    - label: For the market
      range:
        - 12
        - 17
    - label: For non-market institutions
      range:
        - 18
        - 18

  # Unknown labour relations
  unknown:
    label: Unknown
    code: "?"
    color: "#CFD7E7"

  # Combination of multiple labour relations
  multiple:
    label: Either – Or
    code: M
    color: "#517FB5"

# Configuration of time periods (minYear including, maxYear excluding)
timePeriods:
  - timePeriod: 1500
    minYear: 1300
    maxYear: 1580

  - timePeriod: 1650
    minYear: 1580
    maxYear: 1725

  - timePeriod: 1800
    minYear: 1725
    maxYear: 1850

  - timePeriod: 1900
    minYear: 1850
    maxYear: 1925

  - timePeriod: 1950
    minYear: 1925
    maxYear: 1975

  - timePeriod: 2000
    minYear: 1975
    maxYear: 2050

# Configuration of world population by year and continent
worldPopulation:
  label: No data collected
  code: X
  color: "#F9C81F"
  totals:
    1500:
      "Europe": 91544673
      "Asia": 279394636
      "Africa": 46652265
      "North America": 11917625
      "South America": 7914482
      "Oceania": 1124665
    1650:
      "Europe": 123824598
      "Asia": 384641623
      "Africa": 58255896
      "North America": 6958844
      "South America": 4949904
      "Oceania": 1347294
    1800:
      "Europe": 210568152
      "Asia": 655028715
      "Africa": 72136716
      "North America": 19154032
      "South America": 10225724
      "Oceania": 1824200
    1900:
      "Europe": 421298536
      "Asia": 879469356
      "Africa": 110150721
      "North America": 105891122
      "South America": 40858987
      "Oceania": 6224429
    1950:
      "Europe": 568226754
      "Asia": 1387525703
      "Africa": 228182746
      "North America": 220857588
      "South America": 111384890
      "Oceania": 12476128
    2000:
      "Europe": 797849680
      "Asia": 3603869297
      "Africa": 811809059
      "North America": 485941171
      "South America": 349130261
      "Oceania": 30636959

# Mapping countries to continents
countriesToContinent:
  "Afghanistan": "Asia"
  "Albania": "Europe"
  "Antarctica": "Antarctica"
  "Algeria": "Africa"
  "American Samoa (Eastern Samoa)": "Oceania"
  "Andorra": "Europe"
  "Angola": "Africa"
  "Antigua & Barbuda": "North America"
  "Azerbaijan": "Asia"
  "Argentina": "South America"
  "Australia": "Oceania"
  "Austria": "Europe"
  "The Bahamas": "North America"
  "Bahrain": "Asia"
  "Bangladesh": "Asia"
  "Armenia": "Asia"
  "Barbados": "North America"
  "Belgium": "Europe"
  "Bermuda": "North America"
  "Bhutan": "Asia"
  "Bolivia": "South America"
  "Bosnia & Herzegovina": "Europe"
  "Botswana": "Africa"
  "Bouvet I.": "Antarctica"
  "Brazil": "South America"
  "Belize": "North America"
  "British Indian Ocean Territory": "Asia"
  "Solomon Is.": "Oceania"
  "British Virgin Is.": "North America"
  "Brunei": "Asia"
  "Bulgaria": "Europe"
  "Myanmar": "Asia"
  "Burundi": "Africa"
  "Belarus": "Europe"
  "Cambodia": "Asia"
  "Cameroon": "Africa"
  "Canada": "North America"
  "Cape Verde": "Africa"
  "Cayman Is.": "North America"
  "Central African Republic": "Africa"
  "Sri Lanka": "Asia"
  "Chad": "Africa"
  "Chile": "South America"
  "China": "Asia"
  "Taiwan": "Asia"
  "Christmas I.": "Asia"
  "Cocos Is.": "Asia"
  "Colombia": "South America"
  "Comoros": "Africa"
  "Mayotte": "Africa"
  "Congo": "Africa"
  "Congo, DRC": "Africa"
  "Cook Is.": "Oceania"
  "Costa Rica": "North America"
  "Croatia": "Europe"
  "Cuba": "North America"
  "Cyprus": "Asia"
  "Czech Republic": "Europe"
  "Benin": "Africa"
  "Denmark": "Europe"
  "Dominica": "North America"
  "Dominican Republic": "North America"
  "Ecuador": "South America"
  "El Salvador": "North America"
  "Equatorial Guinea": "Africa"
  "Ethiopia": "Africa"
  "Eritrea2": "Africa"
  "Estonia": "Europe"
  "Faroe Is.": "Europe"
  "Falkland Is.": "South America"
  "South Georgia&the South Sandwich Is.": "Antarctica"
  "Fiji": "Oceania"
  "Finland": "Europe"
  "France": "Europe"
  "French Guiana": "South America"
  "French Polynesia": "Oceania"
  "French Southern&Antarctic Lands": "Antarctica"
  "Djibouti": "Africa"
  "Gabon": "Africa"
  "Georgia": "Asia"
  "The Gambia": "Africa"
  "Palestine Territories:Gaza Strip": "Asia"
  "East Germany": "Europe"
  "West Germany": "Europe"
  "Germany": "Europe" # TODO: Missing
  "Ghana": "Africa"
  "Gibraltar (UK)": "Europe"
  "Kiribati": "Oceania"
  "Greece": "Europe"
  "Greenland": "North America"
  "Grenada": "North America"
  "Guadeloupe": "North America"
  "Guam": "Oceania"
  "Guatemala": "North America"
  "Guinea": "Africa"
  "Guyana": "South America"
  "Haiti": "North America"
  "Heard I.&McDonald Is.": "Antarctica"
  "Vatican City": "Europe"
  "Honduras": "North America"
  "Hong Kong (China)": "Asia"
  "Hungary": "Europe"
  "Iceland": "Europe"
  "India": "Asia"
  "Indonesia": "Asia"
  "Iran": "Asia"
  "Iraq": "Asia"
  "Ireland": "Europe"
  "Israel": "Asia"
  "Italy": "Europe"
  "Cote d 'Ivoire": "Africa"
  "Jamaica": "North America"
  "Japan": "Asia"
  "Kazakhstan": "Asia"
  "Jordan": "Asia"
  "Kenya": "Africa"
  "North Korea": "Asia"
  "South Korea": "Asia"
  "Kuwait": "Asia"
  "Kyrgyzstan": "Asia"
  "Laos": "Asia"
  "Lebanon": "Asia"
  "Lesotho": "Africa"
  "Latvia": "Europe"
  "Liberia": "Africa"
  "Libya": "Africa"
  "Liechtenstein": "Europe"
  "Lithuania": "Europe"
  "Luxembourg": "Europe"
  "Macau (China)": "Asia"
  "Madagascar": "Africa"
  "Malawi": "Africa"
  "Malaysia": "Asia"
  "Maldives": "Asia"
  "Mali": "Africa"
  "Malta": "Europe"
  "Martinique": "North America"
  "Mauritania": "Africa"
  "Mauritius": "Africa"
  "Mexico": "North America"
  "Monaco": "Europe"
  "Mongolia": "Asia"
  "Moldova": "Europe"
  "Montenegro": "Europe"
  "Montserrat": "North America"
  "Morocco": "Africa"
  "Mozambique": "Africa"
  "Oman": "Asia"
  "Namibia": "Africa"
  "Nauru": "Oceania"
  "Nepal": "Asia"
  "Netherlands": "Europe"
  "Netherlands Antilles": "North America"
  "Aruba": "North America"
  "Sint Maarten (Neth)": "North America"
  "Bonaire (Neth)": "North America"
  "Saba (Neth)": "North America"
  "Sint Eustatius (Neth)": "North America"
  "New Caledonia": "Oceania"
  "Vanuatu": "Oceania"
  "New Zealand": "Oceania"
  "Nicaragua": "North America"
  "Niger": "Africa"
  "Nigeria": "Africa"
  "Niue": "Oceania"
  "Norfolk Islands": "Oceania"
  "Norway": "Europe"
  "Northern Mariana Is.": "Oceania"
  "Jarvis I.": "Oceania"
  "Micronesia": "Oceania"
  "Marshall Is.": "Oceania"
  "Palau": "Oceania"
  "Pakistan": "Asia"
  "Panama": "North America"
  "Papua New Guinea": "Oceania"
  "Paraguay": "South America"
  "Peru": "South America"
  "Philippines": "Asia"
  "Pitcairn Is.": "Oceania"
  "Poland": "Europe"
  "Portugal": "Europe"
  "Guinea - Bissau": "Africa"
  "Timor Leste": "Asia"
  "Puerto Rico": "North America"
  "Qatar": "Asia"
  "Reunion": "Africa"
  "Romania": "Europe"
  "Russia": "Europe"
  "Rwanda": "Africa"
  "Saint Barthelemy (France)": "North America"
  "St.Helena": "Africa"
  "St.Kitts & Nevis": "North America"
  "Anguilla": "North America"
  "St.Lucia": "North America"
  "Saint Martin (France)": "North America"
  "St.Pierre & Miquelon": "North America"
  "St.Vincent & the Grenadines": "North America"
  "San Marino": "Europe"
  "Sao Tome&Principe": "Africa"
  "Saudi Arabia": "Asia"
  "Senegal": "Africa"
  "Serbia": "Europe"
  "Seychelles": "Africa"
  "Sierra Leone": "Africa"
  "Singapore": "Asia"
  "Slovakia": "Europe"
  "Vietnam": "Asia"
  "Slovenia": "Europe"
  "Somalia": "Africa"
  "South Africa": "Africa"
  "Zimbabwe": "Africa"
  "Spain": "Europe"
  "South Sudan": "Africa"
  "Sudan": "Africa"
  "Western Sahara": "Africa"
  "Suriname": "South America"
  "Jan Mayen": "Europe"
  "Jan Mayen (Norway)": "Europe"
  "Swaziland": "Africa"
  "Sweden": "Europe"
  "Switzerland": "Europe"
  "Syria": "Asia"
  "Tajikistan": "Asia"
  "Thailand": "Asia"
  "Togo": "Africa"
  "Tokelau": "Oceania"
  "Tonga": "Oceania"
  "Trinidad & Tobago": "North America"
  "United Arab Emirates": "Asia"
  "Tunisia": "Africa"
  "Turkey": "Europe"
  "Turkmenistan": "Asia"
  "Turks & Caicos Is.": "North America"
  "Tuvalu": "Oceania"
  "Uganda": "Africa"
  "Ukraine": "Europe"
  "Macedonia": "Europe"
  "Egypt": "Africa"
  "United Kingdom": "Europe"
  "Guernsey": "Europe"
  "Jersey": "Europe"
  "Isle of Man": "Europe"
  "Tanzania": "Africa"
  "United States": "North America"
  "USA": "North America" # TODO: Missing
  "Virgin Is.": "North America"
  "Burkina Faso": "Africa"
  "Uruguay": "South America"
  "Uzbekistan": "Asia"
  "Venezuela": "South America"
  "Wallis & Futuna": "Oceania"
  "Samoa": "Oceania"
  "Yemen": "Asia"
  "Zambia": "Africa"
  "Akrotiri(UK)": "Europe"
  "Ashmore & Cartier Islands(Australia)": "Oceania"
  "Clipperton Island (France)": "North America"
  "Coral Sea Islands (Australia)": "Oceania"
  "Dhekelia (UK)": "Europe"
  "In dispute Belize / Honduras": "North America"
  "In dispute Benin / Burkina Faso": "Africa"
  "In dispute Bhutan / China": "Asia"
  "In dispute Brazil / Uruguay": "South America"
  "In dispute Canada / Denmark": "North America"
  "In dispute China / India": "Asia"
  "In dispute China / Japan / Taiwan": "Asia"
  "In dispute China / Philippines / Taiwan": "Asia"
  "In dispute Comoros / Mayotte / Madagascar": "Africa"
  "In dispute Croatia / Slovenia": "Europe"
  "In dispute Djibouti / Eritrea": "Africa"
  "In dispute Egypt / Saudi Arabia": "Asia"
  "In dispute El Salvador/Honduras": "North America"
  "In dispute Equatorial Guinea/Gabon": "Africa"
  "In dispute India / Nepal": "Asia"
  "In dispute India / Pakistan": "Asia"
  "In dispute Iran / United Arab Emirates": "Asia"
  "In dispute Japan / Russia": "Asia"
  "In dispute Japan / South Korea": "Asia"
  "In dispute Morocco / Spain": "Africa"
  "In dispute South Sudan/Sudan": "Africa"
  "In dispute Spratly Islands": "Asia"
  "In dispute -Paracel Islands": "Asia"
  "Korean islands under UN jurisdiction": "Asia"
  "Kosovo": "Europe"
  "Navassa Island (US)": "North America"
  "No Man 's Land-ISRAEL/West Bank": "Asia"
  "Ceylon": "Asia"
  "China (Ming empire)": "Asia"
  "China (Territory of the Qing dynasty)": "Asia"
  "China (without Xinjiang, Manchuria, Mongolia)": "Asia"
  "India (Deccan: Dharwar)": "Asia"
  "India (Deccan: Khandesh)": "Asia"
  "India (Deccan: Poona)": "Asia"
  "Kyrgyz Republic": "Asia"
  "Libia (Italian and Foreign Population)": "Africa"
  "Palestine": "Asia"
  "Republic of Venice": "Europe"
  "Saint Lucia": "North America"